import 'package:avatar_course2_5_shop/core/utils/size_util.dart';

class ManagerHeight {
  static double h2 = SizeUtil.setHeight(2);
  static double h4 = SizeUtil.setHeight(4);
  static double h6 = SizeUtil.setHeight(6);
  static double h8 = SizeUtil.setHeight(8);
  static double h10 = SizeUtil.setHeight(10);
  static double h12 = SizeUtil.setHeight(12);
  static double h14 = SizeUtil.setHeight(14);
  static double h16 = SizeUtil.setHeight(16);
  static double h18 = SizeUtil.setHeight(18);
  static double h20 = SizeUtil.setHeight(20);
  static double h24 = SizeUtil.setHeight(24);
  static double h26 = SizeUtil.setHeight(26);
  static double h30 = SizeUtil.setHeight(30);
  static double h32 = SizeUtil.setHeight(32);
  static double h34 = SizeUtil.setHeight(34);
  static double h38 = SizeUtil.setHeight(38);
  static double h40 = SizeUtil.setHeight(40);
  static double h50 = SizeUtil.setHeight(50);
  static double h56 = SizeUtil.setHeight(56);
  static double h60 = SizeUtil.setHeight(60);
  static double h70 = SizeUtil.setHeight(70);
  static double h80 = SizeUtil.setHeight(80);
  static double h90 = SizeUtil.setHeight(90);
  static double h100 = SizeUtil.setHeight(100);
  static double h120 = SizeUtil.setHeight(120);
  static double h130 = SizeUtil.setHeight(130);
  static double h140 = SizeUtil.setHeight(140);
  static double h148 = SizeUtil.setHeight(148);
  static double h210 = SizeUtil.setHeight(210);
  static double h220 = SizeUtil.setHeight(220);
  static double h320 = SizeUtil.setHeight(320);
  static double h310 = SizeUtil.setHeight(310);
  static double h450 = SizeUtil.setHeight(450);
  static double h500 = SizeUtil.setHeight(500);
  static double h520 = SizeUtil.setHeight(520);
  static double h600 = SizeUtil.setHeight(600);
  static double h700 = SizeUtil.setHeight(700);
}
