// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYITXHQz_WFu7O6zjUqDgHh8XnJZZsdl8',
    appId: '1:1083493183172:web:3d2fadecd927ea7df16391',
    messagingSenderId: '1083493183172',
    projectId: 'shop-vc2',
    authDomain: 'shop-vc2.firebaseapp.com',
    storageBucket: 'shop-vc2.appspot.com',
    measurementId: 'G-WP8430RVNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0hssGa2ZEByQkpQO-zSeldRfV7XufxAw',
    appId: '1:1083493183172:android:298aba4f92fb9ef5f16391',
    messagingSenderId: '1083493183172',
    projectId: 'shop-vc2',
    storageBucket: 'shop-vc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVjcYcfVWzwSvxNPvRc1C1tXNoDMsvrHw',
    appId: '1:1083493183172:ios:734acffa17083772f16391',
    messagingSenderId: '1083493183172',
    projectId: 'shop-vc2',
    storageBucket: 'shop-vc2.appspot.com',
    iosBundleId: 'com.example.avatarCourse25Shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVjcYcfVWzwSvxNPvRc1C1tXNoDMsvrHw',
    appId: '1:1083493183172:ios:c54a82965f7797f8f16391',
    messagingSenderId: '1083493183172',
    projectId: 'shop-vc2',
    storageBucket: 'shop-vc2.appspot.com',
    iosBundleId: 'com.example.avatarCourse25Shop.RunnerTests',
  );
}
